const recipeslist = [
  {
    id: 1,
        name: "Lumpia Shanghai",
        ingredients: [
        "Ground pork",
        "Minced garlic",
        "Chopped onions",
        "Carrots (julienned)",
        "Soy sauce",
        "Spring roll wrappers",
        "Cooking oil",
        ],
        steps: [
        "1. In a pan, sauté garlic and onions until aromatic.",
        "2. Add ground pork and cook until browned.",
        "3. Add soy sauce and carrots, cook until carrots are tender.",
        "4. Allow the filling to cool, then wrap it in spring roll wrappers.",
        "5. Deep-fry until golden brown and crispy.",
        ],
        tag: "Appetizer",
},

{
    id: 2,
        name: "Tokwat Baboy",
        ingredients: [
        "Tofu",
        "Pork belly (boiled and diced)",
        "Soy sauce",
        "Vinegar",
        "Garlic (minced)",
        "Onion (sliced)",
        "Red chili (optional)",
        ],
        steps: [
        "1. Fry tofu until golden brown and set aside.",
        "2. In a pan, sauté garlic and onions.",
        "3. Add boiled pork and tofu.",
        "4. Pour soy sauce and vinegar, let it simmer until the flavors meld.",
        "5. Garnish with sliced red chili if desired.",
        ],
        tag: "Appetizer",
},

{
    id: 3,
        name: "Kinilaw na Isda (Fish Ceviche)",
        ingredients: [
        "Fresh fish fillet (diced)",
        "Coconut vinegar",
        "Ginger (minced)",
        "Red onion (sliced thinly)",
        "Green chili",
        "Coconut milk (optional)",
        "Salt and pepper to taste",
        ],
        steps: [
        "1. Mix fish, ginger, onion, and green chili in a bowl.",
        "2. Pour coconut vinegar over the mixture.",
        "3. Season with salt and pepper.",
        "4. Optionally, add coconut milk for a creamy texture.",
        "5. Chill before serving.",
        ],
        tag: "Appetizer",
},

{
    id: 4,
        name: "Dynamite (Stuffed Chili Peppers)",
        ingredients: [
        "Green chili peppers",
        "Cheese (cheddar or cream cheese)",
        "Ground pork or ground chicken",
        "Spring roll wrappers",
        "Cooking oil",
        ],
        steps: [
        "1. Slit the chili peppers lengthwise, remove seeds.",
        "2. Stuff each chili with cheese and ground meat.",
        "3. Wrap each chili with spring roll wrappers.",
        "4. Deep-fry until golden brown and crispy.",
        "5. Serve with a dipping sauce.",
        ],
        tag: "Apetizer",
},

{
    id: 5,
        name: "Adobong Mani (Garlic Peanuts)",
        ingredients: [
        "Raw peanuts",
        "Garlic (minced)",
        "Soy sauce",
        "Sugar",
        "Cooking oil",
        ],
        steps: [
        "1. In a pan, roast peanuts until golden brown.",
        "2. Set aside the roasted peanuts.",
        "3. In the same pan, sauté garlic until fragrant.",
        "4. Add soy sauce and sugar, then mix in the peanuts.",
        "5. Cook until the peanuts are coated and the mixture is slightly caramelized.",
        ],
        tag: "Appetizer",
},
{
    id: 6,
        name: "Halo-Halo",
        ingredients: [
        "Shaved ice",
        "Evaporated milk",
        "Condensed milk",
        "Ube (purple yam) halaya",
        "Leche flan (caramel custard)",
        "Sweetened bananas",
        "Jackfruit strips",
        "Nata de coco (coconut jelly)",
        "Sweetened red mung beans",
        "Shredded coconut",
        "Tapioca pearls",
        ],
        steps: [
        "1. Layer shaved ice in a bowl or glass",
        "2. Add various toppings such as sweetened fruits, jellies, and beans.",
        "3. Drizzle with evaporated milk and condensed milk.",
        "4. Top with ube halaya and leche flan.",
        "5. Mix thoroughly before enjoying this delightful mix of flavors and textures.",
        ],
        tag: "Dessert",
},

{
    id: 7,
        name: "Halo-Halo",
        ingredients: [
        "Egg yolks",
        "Condensed milk",
        "Evaporated milk",
        "Sugar",
        "Vanilla extract (optional)",
        ],
        steps: [
        "1. Caramelize sugar in a llanera (mold) to create a syrup.",
        "2. In a bowl, mix egg yolks, condensed milk, evaporated milk, and vanilla extract.",
        "3. Strain the mixture to achieve a smooth consistency.",
        "4. Pour the mixture into the llanera over the caramelized sugar.",
        "5. Steam until the leche flan is set, then chill before serving.",
        ],
        tag: "Dessert",
},

{
    id: 8,
        name: "Bibingka",
        ingredients: [
        "Rice flour",
        "Coconut milk",
        "Sugar",
        "Baking powder",
        "Salted egg",
        "Grated coconut",
        "Butter",
        ],
        steps: [
        "1. Mix rice flour, coconut milk, sugar, and baking powder to form a batter.",
        "2. Pour the batter into banana leaves lined pans.",
        "3. Top with slices of salted egg and grated coconut.",
        "4. Bake until the bibingka is cooked and has a golden crust.",
        "5. Serve warm with butter and grated coconut.",
        ],
        tag: "Dessert",
},

{
    id: 9,
        name: "Turon (Banana Lumpia)",
        ingredients: [
        "Ripe bananas",
        "Brown sugar",
        "Jackfruit strips",
        "Spring roll wrappers",
        "Cooking oil",
        ],
        steps: [
        "1. Roll each banana in brown sugar.",
        "2. Place a banana and jackfruit strip on a spring roll wrapper.",
        "3. Roll it into a tight log, sealing the edge with water.",
        "4. Deep-fry until golden brown and crispy.",
        "5. Drain excess oil and let it cool before serving.",
        ],
        tag: "Dessert",
},

{
    id: 10,
        name: "Turon (Banana Lumpia)",
        ingredients: [
        "Glutinous rice",
        "Purple food coloring",
        "Coconut shreds",
        "Butter",
        "Sugar",
        ],
        steps: [
        "1. Soak glutinous rice overnight.",
        "2. Grind the rice and mix with purple food coloring.",
        "3. Fill bamboo tubes with the rice mixture and steam until cooked.",
        "4. Remove from the tubes, top with butter, sugar, and coconut shreds.",
        "5. Serve warm, traditionally enjoyed during Christmas season.",
        ],
        tag: "Dessert",
},

{
    id: 11,
        name: "Turon (Banana Lumpia)",
        ingredients: [
        "Glutinous rice",
        "Purple food coloring",
        "Coconut shreds",
        "Butter",
        "Sugar",
        ],
        steps: [
        "1. Soak glutinous rice overnight.",
        "2. Grind the rice and mix with purple food coloring.",
        "3. Fill bamboo tubes with the rice mixture and steam until cooked.",
        "4. Remove from the tubes, top with butter, sugar, and coconut shreds.",
        "5. Serve warm, traditionally enjoyed during Christmas season.",
        ],
        tag: "Dessert",
},

{
    id: 11,
        name: "Buko Juice (Coconut Water)",
        ingredients: [
        "Fresh young coconut",
        "Ice cubes",
        "Simple syrup (optional)",
        ],
        steps: [
        "1. Open a young coconut to extract the coconut water.",
        "2. Pour the coconut water into a glass over ice.",
        "3. Optionally, add simple syrup for sweetness.",
        "4. Stir well and enjoy this natural and hydrating drink.",
        ],
        tag: "Drinks",
},

{
    id: 12,
        name: "Sago't Gulaman",
        ingredients: [
        "Tapioca pearls (sago)",
        "Gelatin cubes (gulaman)",
        "Brown sugar",
        "Water",
        "Crushed ice",
        "Pandan leaves (optional)",
        ],
        steps: [
        "1. Cook tapioca pearls and gelatin cubes separately according to package instructions.",
        "2. Dissolve brown sugar in water to make arnibal.",
        "3. Combine sago, gulaman, arnibal, and pandan leaves (optional).",
        "4. Serve over crushed ice for a sweet and chewy drink.",
        ],
        tag: "Drinks",
},

{
    id: 13,
        name: "Calamansi Juice",
        ingredients: [
        "Calamansi (Philippine lime)",
        "Water",
        "Sugar or honey",
        "Ice cubes",
        ],
        steps: [
        "1. Squeeze calamansi to extract the juice.",
        "2. Mix the calamansi juice with water.",
        "3. Sweeten with sugar or honey to taste.",
        "4. Serve over ice for a tangy and refreshing beverage.",
        ],
        tag: "Drinks",
},

{
    id: 14,
        name: "Guyabano Shake",
        ingredients: [
        "Guyabano (soursop) pulp",
        "Milk",
        "Ice cubes",
        "Sugar or condensed milk (optional)",
        ],
        steps: [
        "1. Blend guyabano pulp, milk, and ice until smooth.",
        "2. Sweeten with sugar or condensed milk if desired.",
        "3. Pour into a glass and enjoy this creamy and tropical shake.",
        ],
        tag: "Drinks",
},
{
    id: 15,
        name: "Barako Coffee",
        ingredients: [
        "Barako coffee beans (native Philippine coffee)",
        "Water",
        "Sugar or condensed milk (optional)",
        ],
        steps: [
        "1. Grind Barako coffee beans to your preferred coarseness.",
        "2. Brew the coffee using a traditional Filipino coffee maker or any brewing method.",
        "3. Sweeten with sugar or condensed milk to taste.",
        "4. Savor the strong and bold flavor of this local coffee.",
        ],
        tag: "Drinks",
},
{
  id: 16, 
  name: "Egg Fried Rice",
    ingredients: [ 
      "1 cup water", " 2 tablespoons soy sauce",
      "½ teaspoon salt”, “1 cup uncooked instant rice", 
      "1 teaspoon vegetable oil",
      "½ onion, finely chopped","½ onion, finely chopped½ cup sliced green beans or peas","1 large egg, lightly beaten",
    ],
 steps: [ 
  "1. Bring water, soy sauce, and salt to a boil in a medium saucepan. Stir in instant rice and remove from heat. Cover and let stand for 5 minutes.",
  "2. Heat oil in a medium skillet or wok over medium heat. Sauté onions and green beans in hot oil for 2 to 3 minutes. Pour in beaten egg and fry for 2 minutes, scrambling egg while it cooks.",
  "3. Add cooked rice to egg mixture; mix well. Season with pepper.",
  "4. Serve hot and enjoy!",
  ], 
  tag: "Breakfast",
},
{
  id: 17, 
  name: "Fried Milk Fish with Garlic Rice",
    ingredients: [ 
    "1 deboned milk fish", " 3 tablespoon soy sauce",
    "½ a lemon or 1 tbsp kalamansi", "1 pinch ground black pepper",
  ],
  steps: [ 
    "1. Place fish in a plate or bowl, add soy, lemon and black pepper leave it to marinate for 30 minutes to 1 hours. Overnight is also  good, the longer it marinates the tastier. ",
    "2. Using a medium frying pan, heat up the oil. Fry the milk fish until crisp and golden brown on each  side.",
    "3. It’s best served with garlic fried rice, fried rice and fried eggs.",
], tag: "Breakfast",
},
{
  id: 18, 
  name: "Arroz caldo",
    ingredients: [ 
      "200g jasmine rice", " 300g chicken,cubed",
      "150g ginger, cruched &  julienne", "1 large onions, julliene",
       "3 litres water", "1 ¼ tablespoon salt", "1 teaspoon ground pepper","3 tablespoon cooking oil","3 boiled eggs for toppings","2 stems spring onions for toppings", "3 tablespoon fish sauce, option","1 tablespoon crunch garlic",
    ],
 steps: [ 
    "1. In a large cooking pot heat some oil, saute ginger for 2 minutes, followed by some onions and cook for another 2 minutes. Add chicken, cook until the meat turns white then add rice. Mix all the ingredients while cooking it for another 1-2 minutes. Add 1 litre of water and bring it to boil on high heat.",
    "2. Turn the heat down, add salt, ground pepper and simmer the porridge for 30-40 minutes or until the starch from the rice starts to come out, rice grain is open and soft. Continue to add water and stir when the porridge becomes too thick. You don’t have to stir the whole time but make sure the porridge doesn’t dry out and stick at the bottom of the pan.",
    "3. Prepare your condiments and toppings while waiting the porridge is simmering. You can add as many or as little toppings as you want!.",
    "4. Check the porridge and taste it, you can add more salt at this stage if you want. I like my Arroz Caldo not too thick, I approximately add about 2 litres of water throughout cooking it. You will know that the porridge is ready when the individual rice opens and the porridge is thick and starchy.",
    "5. When you are happy with your porridge you can turn the heat off. Arroz caldo is best serve hot. Be careful not to burn your tongue! HAHA! I pour some Arroz caldo in a bowl, add my toppings and finished with some lemon or kalamansi.",
 ], tag: "Breakfast",
},
{
  id: 19, name: "Charred Aubergine Omelette (Tortang Talong)",
    ingredients: [ 
      "2 aubergine", 
      " 2 eggs",
      "pinch of salt", 
      "pinch of ground black pepper",
       "cooking oil", 
 ],
 steps: [ 
    "1. You can char aubergine in your grill oven or on a bbq or gas stove. Before cooking the aubergine or egg plants, poke it couple of times using a knife of fork.",
    "2.Cook until soft and the skin has separated from the flesh. Don’t worry if the skin is burnt it’s part of the process. Turn aubergine every so often. Take it out of the oven grill or bbq and let it cool down on the side..",
    "3. Beat eggs in a bowl, season with salt and pepper.",
    "4. Leave on the side for later. Peel the skin off the aubergine leaving the stem, using a fork press and flatten the aubergine then add it into the eggs and mix well.",
 ], tag: "Breakfast",
},
{
  id: 20, 
  name: "Charred Aubergine Omelette (Tortang Talong)",
    ingredients: [ 
    "1 cup glutinous rice (malagkit)",
     " 1 cup regular rice",
      "1 cup beef tripe, cleaned and sliced into thin strips",
      "1/2 cup ginger, minced", 
      "1/2 cup garlic, minced",
      "1 medium-sized onion, chopped",
      "8 cups water",
      "1 beef bouillon cube( optional, for added flavor)", 
      "Salt and pepper to  taste",
 ],
 steps: [ 
    "1. Rinse the glutinous rice and regular rice under cold water until the water runs clear.",
    "2. In a large pot, combine the glutinous rice, regular rice, beef tripe, ginger, garlic, onion, and water. Bring the mixture to a boil.",
    "3. Once boiling, reduce the heat to low and let it simmer. Stir occasionally to prevent the rice from sticking to the bottom of the pot.",
    "4. If using, add the beef bouillon cube for added flavor. Continue to simmer until the rice is fully cooked and the mixture thickens to your desired consistency.",
    "5.Season with salt and pepper to taste. Adjust the seasoning according to your preference",
    "6. Serve the Goto hot in bowls, and garnish with toppings such as hard-boiled eggs, fried garlic, chopped green onions, and calamansi or lemon wedges.”,"
 ], tag: "Breakfast",
},
{
  id: 21,
  name: "Adobo (Chicken or Pork)",
  ingredients: [ 
    "Chicken or pork piece", 
    " Soy sauce",
    "Vinegar", 
    "Garlic, minced", 
    "Bay leaves", 
    "Cooking oil",
 ],
 steps: [ 
    "1. Marinate meat in soy sauce, vinegar, minced garlic, pepper, and bay leaves for at least 30 minutes.",
    "2.Saute marinated meat in oil until brown.",
    "3. Add the marinade and summer until the meat is tender and the sauce thickens.",
  ], tag: "Lunch",
},
{
  id: 22, 
  name: "Sinigang na Baboy",
  ingredients: [ 
    "Pork ribs or belly", 
    "Tamarid mix or fresh tamarind",
    "Radish", 
    "String beans", 
    "String beans", 
    "Eggplant",
    "Fish sauce",
 ],
 steps: [ 
    "1. Boil pork in water until tender",
    "2.Add tamarind mix or fresh tamarind for sourness.",
    "3. Add vegetables and cook until they’re tender",
    "4. Season with fish sauce to taste",
  ], tag: "Lunch",
},
{
  id: 23, 
  name: "Pancit Canton",
  ingredients: [ 
    "Canton noodles", 
    "Chicken breast or pork, thinly sliced",
    "Shrimp", 
    "Soy sauce", 
    "Oyster sauce", 
    "Carrots and Cabbage",
    "Garlic, minced",
 ],
 steps: [ 
    "1. Cook noodles according to package intstructions",
    "2.Saute garlic, add chicken/pork, shrimp, and vegetables",
    "3. Mix in cooked noodles and season with soy sauce and oyster sauce",
  ], tag: "Lunch",
},
{
  id: 24, name: "Kare-Kare",
  ingredients: [ 
    "Ox tripe and/or oxtail", 
    "Peanut butter",
    "Annatto seeds (achuete)", 
    "String beans", 
    "Banana hearts (puso ng saging)", 
    " Egg[lant",
    "Ground rice (to thicken) ",
 ],
 steps: [ 
    "1. Boil meat until tender, then set aside. ",
    "2.Saute annatto seeds in oil, add peanut butter and ground rice.",
    "3. Pour in water, add the bolied meat, and vegetables. Simmer until cooked.",
  ], tag: "Lunch",
},
{
  id: 25, name: "Lechon Kawali",
  ingredients: [ 
    "Pork belly", 
    "Salt",
    "Salt", 
    "Pepper", 
    "Oil for deep frying",
 ],
 steps: [ 
    "1. Boil pork belly with salt and pepper until tender.",
    "2.Air-dry or refrigerate the boiled pork to dry the skin.",
    "3. Deep-fry until the skin is crispy and meat is golden brown,",
  ], tag: "Lunch",
},

{
  id: 26,
  name: "Chicken Adobo",
  ingredients: [
    "1 kg chicken pieces (thighs and drumsticks)",
    "1/2 cup soy sauce",
    "1/2 cup vinegar",
    "4 cloves garlic, minced",
    "1 onion, sliced",
    "1 bay leaf",
    "1 teaspoon whole peppercorns",
    "1 tablespoon cooking oil",
  ],
  steps: [
    "1. In a pot, combine chicken, soy sauce, vinegar, garlic, onion, bay leaf, and peppercorns.",
    "2. Marinate for at least 30 minutes.",
    "3. Bring to a boil, then lower the heat and simmer until chicken is tender, about 30-40 minutes.",
    "4. Heat oil in a pan and fry the chicken until browned.",
    "5. Serve hot with steamed rice.",
  ],
  tag: "Dinner",
},
{
  id: 27,
  name: "Chicken Tinola",
  ingredients: [
    "1 kg chicken pieces",
    "2 thumbs ginger, sliced",
    "6 cloves garlic, minced",
    "1 onion, sliced",
    "1 green papaya, peeled, seeded, and sliced",
    "2 cups chili leaves or spinach",
    "2 tablespoons fish sauce",
  ],
  steps: [
    "1. Sauté ginger, garlic, and onion.",
    "2. Add chicken and cook until slightly browned.",
    "3. Add water and simmer until chicken is tender.",
    "4. Add green papaya and cook until soft.",
    "5. Add chili leaves and season with fish sauce.",
  ],
  tag: "Dinner",
},
{
  id: 28,
  name: "Bistek Tagalog ",
  ingredients: [
    "500g beef sirloin, thinly sliced",
    "1/2 cup soy sauce",
    "1/4 cup calamansi juice or lemon juice",
    "4 cloves garlic, minced",
    "1 onion, sliced into rings",
    "2 tablespoons cooking oil",
    "Salt and pepper to taste",
  ],
  steps: [
    "1. Marinate beef slices in soy sauce, calamansi juice, garlic, salt, and pepper for at least 30 minutes.",
    "2. In a pan, heat oil and sauté onion rings until caramelized. Set aside.",
    "3. In the same pan, sear marinated beef slices until browned.",
    "4. Pour the marinade over the beef and simmer until the sauce thickens.",
    "5. Top with caramelized onions before serving.",
  ],
  tag: "Dinner",
},
{
  id: 29,
  name: "Pinakbet",
  ingredients: [
    "1 small bitter melon (ampalaya), sliced",
    "1 medium-sized eggplant, sliced",
    "2 pieces small squash (kalabasa), cubed",
    "100g string beans (sitaw), cut into 2-inch pieces",
    "1 tomato, sliced",
    "1 onion, sliced",
    "3 cloves garlic, minced",
    "100g pork belly, sliced",
    "2 tablespoons shrimp paste (bagoong)",
    "1 cup water",
    "Cooking oil",
  ],
  steps: [
    "1. In a pan, sauté garlic and onion until fragrant.",
    "2. Add pork belly and cook until browned.",
    "3. Add tomatoes and cook until soft.",
    "4. Stir in shrimp paste and pour water. Let it simmer.",
    "5. Add bitter melon, eggplant, squash, and string beans. Cook until vegetables are tender.",
    "6. Serve hot with steamed rice.",
  ],
  tag: "Dinner",
},
{
  id: 30,
  name: "Bangus Belly Steak",
  ingredients: [
    "500g milkfish (bangus) belly, cleaned and sliced",
    "1/4 cup soy sauce",
    "1/4 cup calamansi juice or lemon juice",
    "4 cloves garlic, minced",
    "1 onion, sliced into rings",
    "2 tablespoons cooking oil",
    "Salt and pepper to taste",
  ],
  steps: [
    "1. Marinate milkfish belly slices in soy sauce, calamansi juice, garlic, salt, and pepper for at least 30 minutes.",
    "2. In a pan, heat oil and sear marinated milkfish belly slices until cooked.",
    "3. Remove from pan and set aside.",
    "4. In the same pan, sauté onion rings until caramelized.",
    "5. Serve caramelized onions on top of the cooked milkfish belly slices.",
  ],
  tag: "Dinner",
},
];
module.exports = { recipeslist };
